# Generated by Django 5.1.15 on 2026-08-16 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(choices=[('接单', '接单'), ('排产', '排产'), ('生产中', '生产中'), ('质检', '质检'), ('发货', '发货'), ('签收', '签收'), ('结算', '结算'), ('回款', '回款'), ('已取消', '已取消')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('is_reject', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tracking/%Y%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tracking.trackinglog')),
            ],
        ),
    ]
