# Generated by Django 5.1.15 on 2026-08-22 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0006_customer_tracker'),
        ('orders', '0003_remove_orderitem_factory_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('tracking_no', models.CharField(blank=True, max_length=128)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_currency', models.CharField(choices=[('CNY', '人民币'), ('USD', '美元')], default='CNY', max_length=8)),
                ('payer', models.CharField(choices=[('customer', '客户'), ('company', '公司'), ('factory', '工厂')], default='company', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domestic_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domestic_shipments', to='basic_info.logisticsprovider')),
                ('intl_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intl_shipments', to='basic_info.logisticsprovider')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
            options={
                'ordering': ['order', 'seq'],
            },
        ),
    ]
