# Generated by Django 5.1.15 on 2026-09-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0007_alter_customer_name'),
        ('logistics', '0002_logistics_is_approved'),
        ('orders', '0006_exchangerate_exchangerate_pair_date_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='logistics',
            constraint=models.UniqueConstraint(fields=('order', 'seq'), name='logistics_order_seq_unique'),
        ),
    ]
