# Generated by Django 5.1.15 on 2026-08-12 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=64, unique=True)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('spec', models.TextField(blank=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('default_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='basic_info.category')),
            ],
        ),
    ]
