# Generated by Django 5.1.15 on 2026-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0006_customer_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
