# Generated by Django 5.1.15 on 2026-08-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0006_customer_tracker'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('ali_status', models.CharField(blank=True, max_length=32)),
                ('tracking_status', models.CharField(blank=True, choices=[('接单', '接单'), ('排产', '排产'), ('生产中', '生产中'), ('质检', '质检'), ('发货', '发货'), ('签收', '签收'), ('结算', '结算'), ('回款', '回款'), ('已取消', '已取消')], max_length=16)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('carrier', models.CharField(blank=True, max_length=64)),
                ('logistics_method', models.CharField(blank=True, max_length=64)),
                ('tracking_no', models.CharField(blank=True, max_length=128)),
                ('remark', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('order_profit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='basic_info.customer')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('product_no', models.CharField(blank=True, max_length=64)),
                ('spec', models.TextField(blank=True)),
                ('qty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('factory_payment_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_info.factory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_info.product')),
            ],
        ),
    ]
