# Generated by Django 5.1.15 on 2026-08-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='factory_payment_id',
        ),
    ]
