# Generated by Django 5.1.15 on 2026-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_approved'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchangerate_rate_positive'),
        ),
    ]
