# Generated by Django 5.1.15 on 2026-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_exchangerate_exchangerate_rate_positive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency_pair', 'effective_date'), name='exchangerate_pair_date_unique'),
        ),
    ]
