# Generated by Django 5.1.15 on 2026-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0005_exchangerate_exchangerate_rate_positive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentin',
            constraint=models.CheckConstraint(condition=models.Q(('amount_usd__gt', 0)), name='paymentin_amount_positive'),
        ),
    ]
