# Generated by Django 5.1.15 on 2026-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentin_paymentin_amount_positive'),
        ('orders', '0006_exchangerate_exchangerate_pair_date_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentin',
            constraint=models.UniqueConstraint(fields=('order', 'installment'), name='paymentin_order_installment_unique'),
        ),
    ]
