# Generated by Django 5.1.15 on 2026-09-17 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentin_paymentin_order_installment_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentin',
            name='installment',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
