# Generated by Django 5.1.15 on 2026-08-21 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0006_customer_tracker'),
        ('orders', '0003_remove_orderitem_factory_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cny', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='未结', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_payments', to='basic_info.factory')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factory_payment', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='factory_payment.factorypayment')),
            ],
        ),
    ]
