# Generated by Django 5.1.15 on 2026-08-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorypayment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='factorypaymentrecord',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
