# Generated by Django 5.1.15 on 2026-09-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0006_customer_tracker'),
        ('factory_payment', '0002_factorypayment_is_approved_and_more'),
        ('orders', '0005_exchangerate_exchangerate_rate_positive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='factorypayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cny__gt', 0)), name='fp_amount_cny_positive'),
        ),
        migrations.AddConstraint(
            model_name='factorypaymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='fp_record_amount_positive'),
        ),
    ]
